"""drop old_models table

Revision ID: 120b2ecadf5d
Revises: 890abc86213d
Create Date: 2026-06-11 15:07:57.468225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120b2ecadf5d'
down_revision: Union[str, None] = '890abc86213d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraints first (safe)
    op.drop_constraint(
        "lesson_translations_lesson_id_fkey",
        "lesson_translations",
        type_="foreignkey"
    )

    op.drop_constraint(
        "student_progress_lesson_id_fkey",
        "student_progress",
        type_="foreignkey"
    )

    # Drop tables (NOW safe)
    op.drop_table("lesson_translations")
    op.drop_table("lessons")

    # Update student_progress → unit_id only
    op.drop_column("student_progress", "lesson_id")
    op.add_column(
        "student_progress",
        sa.Column("unit_id", sa.Integer(), nullable=False)
    )

    op.create_foreign_key(
        "student_progress_unit_id_fkey",
        "student_progress",
        "units",
        ["unit_id"],
        ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_progress', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_progress', type_='foreignkey')
    op.create_foreign_key(op.f('student_progress_lesson_id_fkey'), 'student_progress', 'lessons', ['lesson_id'], ['id'])
    op.drop_column('student_progress', 'unit_id')
    op.add_column('lesson_translations', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lesson_translations', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_translations_lesson_id_fkey'), 'lesson_translations', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint('uq_lesson_language', 'lesson_translations', type_='unique')
    op.create_unique_constraint(op.f('uq_lesson_language'), 'lesson_translations', ['lesson_id', 'language_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('lesson_translations', 'unit_id')
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('lesson_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('lessons_unit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey'))
    )
    # ### end Alembic commands ###
