"""add thumbnail to units

Revision ID: 890abc86213d
Revises: c8fa824e8b64
Create Date: 2026-06-11 14:07:06.122298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890abc86213d'
down_revision: Union[str, None] = 'c8fa824e8b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('units', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'is_published')
    op.drop_column('units', 'thumbnail')
    # ### end Alembic commands ###
