"""add access_type to lesson_translations

Revision ID: 935df9c155a0
Revises: 2b3a9a90d9f8
Create Date: 2026-07-13 11:40:52.380739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935df9c155a0'
down_revision: Union[str, None] = '2b3a9a90d9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_translations', sa.Column('access_type', sa.String(length=20), server_default='FREE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_translations', 'access_type')
    # ### end Alembic commands ###
