"""add thumbnail to subjects

Revision ID: c8fa824e8b64
Revises: 1b96f3f45cec
Create Date: 2026-06-11 11:38:17.104729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fa824e8b64'
down_revision: Union[str, None] = '1b96f3f45cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'is_active')
    op.drop_column('subjects', 'thumbnail')
    # ### end Alembic commands ###
