"""add grade_id to subjects

Revision ID: ea4b156e56c3
Revises: 935df9c155a0
Create Date: 2026-07-13 12:34:10.205511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4b156e56c3'
down_revision: Union[str, None] = '935df9c155a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'grades', ['grade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'grade_id')
    # ### end Alembic commands ###
